# This file lists the exe file names to keep the main.py and monitor_and_block.py files cleaner
# It includes RCA App installer exe files as well.

# Uses a set for effiency, non-changeability, and no duplicates.
EXE_NAME_LIST = {
    'action1client.exe',
    'aeroadmin.exe',
    'anydesk.exe',
    'anyviewer.exe',
    'AnyViewerSetup.tmp', 
    'RCClient.exe',
    'bomgar.exe',
    'chromeremotedesktop.exe',
    'connectwisecontrol.client.exe',
    'distant-desktop.exe',
    'dsktopnow.exe',
    'dwagent.exe',
    'g2pc.exe',
    'getscreen.exe',
    'HelpWire Quick.exe',
    'iperiusconsole.exe',
    'IperiusRemote_Setup.exe',
    'isllight.exe',
    'ISL Light Client.exe',
    'jumpdesktop.exe',
    'JumpDesktopConnect.exe',
    'litemanager.exe',
    'LiteManager Pro - Server.msi',
    'LiteManager Pro - Viewer.msi',
    'LMNoIpServer.exe',
    'logmein.exe',
    'mikogo.exe',
    'mstsc.exe',
    'nxplayer.exe',
    'quickassist.exe',
    'Quick Assist Installer.exe',
    'remotepc.exe',
    'RemotePCHost.exe',
    'RemotePCViewer.exe',
    'ROMServer.exe',
    'rustdesk.exe',
    'rustdesk-1.2.3-2-x86_64.exe',
    'splashtop.exe',
    'SplashtopSOS.exe',
    'TeamViewer.exe',
    'TeamViewerQS_x64.exe',
    'TeamViewer_Host_Setup_x64.exe',
    'TeamViewer_Setup_x64.exe',
    'TeamViewerMeeting_Setup_x64.exe',
    'tvnserver.exe',
    'tvnviewer.exe',
    'UltraVNC_1436_X86_Setup.exe',
    'UltraVNC_1436_X64_Setup.exe',
    'vncserver.exe',
    'vncviewer.exe',
    'VNC-Viewer-7.11.1-Windows.exe',
    'VNC-Connect-Installer-2.2.2-Windows.exe',
    'VNC-Server-7.11.1-Windows.exe',
    'winvnc.exe',
    'zohoassist.exe'
}


# Listed programs:
#   TeamViewer, AnyDesk, RemotePC, VNC Connect, SplashTop, Zoho Assist, ConnectWise, BeyondTrust, AnyViewer,
#   DWService, Getscreen.me, Chrome Remote Desktop, Windows Remote Desktop, AnyViewer, RustDesk, Distand Desktop, AeroAdmin,
#   Quick Assist, UltraVNC, Jump Desktop, Iperius Remote, LiteManager, DesktopNow, LogMeIn, ISL Online, Action1, 